name: clinexa_doctor
description: "Clinexa Doctor App - A mobile application for clinic management"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.8
  get_it: ^9.2.0
  go_router: ^14.0.0
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  iconsax: ^0.0.8
  toastification: ^2.3.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  pretty_bloc_observer: ^1.0.4
  dartz: ^0.10.1
  shimmer: ^3.0.0
  pretty_dio_logger: ^1.4.0
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/lang/
    - assets/env/.env.dev
    - assets/env/.env.prod
